In [6]:
import pandas as pd
from snowflake.snowpark import Session
from snowflake.snowpark.functions import col

C:\Users\joysn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\snowflake\connector\options.py:104: UserWarning: You have an incompatible version of 'pyarrow' installed (20.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
  warn_incompatible_dep(

In [2]:
df = pd.read_csv(r"C:\Users\joysn\Desktop\retail_sales_dataset.csv")

In [3]:
df

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

In [14]:
#connection parameters

conn = {
    'user' : 'joy3',
    'password' : 'Datapass3698@@',
    'account' : 'WGULHNB-XJC50608',
    'warehouse' : 'my_wh',
    'database' : 'retail',
    'schema' : 'PUBLIC'
}
session = Session.builder.configs(conn).create()
session.write_pandas(df, table_name="raw_retail_sales", auto_create_table=True, overwrite=True)

In [20]:
query = """
WITH retail_sales AS(SELECT TO_DATE("Date", 'YYYY-MM-DD') AS "sale_date",
"Customer ID" AS "customer_id", 
"Gender" AS "gender",
"Age" AS "age",
"Product Category" AS "product_category",
"Quantity" AS "quantity",
"Price per Unit" AS "price_per_unit",
"Total Amount" AS "total_amount"
FROM "raw_retail_sales")

SELECT * FROM retail_sales
"""

retail = session.sql(query).to_pandas()

In [21]:
retail

,sale_date,customer_id,gender,age,product_category,quantity,price_per_unit,total_amount
0,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,2023-05-06,CUST005,Male,30,Beauty,2,50,100
...,...,...,...,...,...,...,...,...
995,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,2023-04-12,CUST1000,Male,47,Electronics,4,30,120